import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header/Header";
import Filters from "../components/nav/Filters";
import Movies from "../components/Movies/Movies";
import { useRef } from "react";
import requests from "../utils/requests";

import { useRouter } from "next/router";
import useScroll from "../Hooks/useScroll";

export default function Home(props) {
	const loader = useRef(null);
	const { list } = useScroll(loader);

	return (
		<div>
			<Head>
				<title>Create Next App | Hulu</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<Filters />
			<Movies initial={props.initialList} loaded={list} />
			<div id="interceptor" ref={loader}></div>
		</div>
	);
}

//FIRST 2 RENDERS QUERY IS EMPTY SO THIS PROPS ARE CRUTIAL
//also fetches first page of movies
export async function getServerSideProps(context) {
	const genre = context.query.genre || "";
	const result = await fetch(
		`https://api.themoviedb.org/3${
			requests[genre]?.url || requests.Trending.url
		}&page=1`
	).then((data) => data.json());

	return {
		props: {
			genre,
			initialList: result.results,
		},
	};
}
